version: '3'
services:
  energy-monitor:
    build: .
    restart: always
    environment:
    - MODBUS_HOST=192.168.0.99
    - MODBUS_PORT=502
    - MODBUS_ADDRESS=101
    - INFLUX_URL=http://192.168.0.100:8086
    - INFLUX_BUCKET=home
    - INFLUX_ORG=home
    - INFLUX_TOKEN=
    - INFLUX_MEASUREMENT=energy
    - INFLUX_METERTAG=main
    #- BALANCED_KWH_TOTALS_FILE=/energymonitor/balancedKwhTotals.json # Location of the file where the balanced total kwh is saved
    #- HTTP_PORT=80 # if you want to expose the read values via HTTP as well, you can enter a port number
    #- INFLUX_MAP_FILE=/energymonitor/influx_map.json # If you want to overwrite it, you can provide your own by setting a location via a volume
    - INTERVAL=1000 # We need 4 round trips to retrieve all modbus registers, so don't shrink the interval too much
    #ports:
    #- "80:80"
  #volumes:
  #  - /home/home/energy-monitor/influx_map.json:/energymonitor/influx_map.json
  #  - /home/home/energymonitor/balancedKwhTotals.json:/energymonitor/balancedKwhTotals.json
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"